project:
  type: website
  output-dir: docs

website:
  title: "ISSS608-VAA"
  navbar:
    background: "#1A472A"
    foreground: "#D1D1D1"
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands on Exercise/Hands on Exercise_1/Hands-on Exercise_1.html"
          - text: "Hands-on Exercise 2"
            href: "Hands on Exercise/Hands on Exercise_2/Hands-on Exercise_2.html"
          - text: "Hands-on Exercise 3-1"
            href: "Hands on Exercise/Hands on Exercise_3/Hands-on Exercise_3_1.html"
          - text: "Hands-on Exercise 3-2"
            href: "Hands on Exercise/Hands on Exercise_3/Hands-on Exercise_3_2.html"
          - text: "Hands-on Exercise 4-1"
            href: "Hands on Exercise/Hands on Exercise_4/Hands-on Exercise_4_1.html"
          - text: "Hands-on Exercise 4-2"
            href: "Hands on Exercise/Hands on Exercise_4/Hands-on Exercise_4_2.html"
          - text: "Hands-on Exercise 4-3"
            href: "Hands on Exercise/Hands on Exercise_4/Hands-on Exercise_4_3.html"
          - text: "Hands-on Exercise 4-4"
            href: "Hands on Exercise/Hands on Exercise_4/Hands-on Exercise_4_4.html"
          - text: "Hands-on Exercise 5"
            href: "Hands on Exercise/Hands on Exercise_5/Hands-on Exercise_5.html"
          - text: "Hands-on Exercise 6"
            href: "Hands on Exercise/Hands on Exercise_6/Hands-on Exercise_6.html"
          - text: "Hands-on Exercise 7"
            href: "Hands on Exercise/Hands on Exercise_7/Hands-on Exercise_7.html"
          - text: "Hands-on Exercise 8"
            href: "Hands on Exercise/Hands on Exercise_8/Hands-on Exercise_8.html"
          - text: "Hands-on Exercise 9"
            href: "Hands on Exercise/Hands on Exercise_9/Hands-on Exercise_9.html"
          - text: "Hands-on Exercise 10"
            href: "Hands on Exercise/Hands on Exercise_10/Hands-on-Exercise_10.html"
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual