project:
  type: website
  output-dir: docs

website:
  title: "<img src='/image/hat.png' style='height: 50px; vertical-align:middle; margin-right:15px;'> ISSS608-VAA"
  navbar:
    background: "#1A472A"
    foreground: "#D1D1D1"
    left:
      - text: "<img src='/image/golden.png' style='height:30px; vertical-align:middle; margin-right:8px;'> Hands-on Exercise"
        menu:
          - text: "1. A Layered Grammar of Graphics: ggplot2 methods"
            href: "Hands on Exercise/Hands on Exercise_1/Hands-on Exercise_1.html"
          - text: "2. Beyond ggplot2 Fundamentals"
            href: "Hands on Exercise/Hands on Exercise_2/Hands-on Exercise_2.html"
          - text: "3a. Programming Interactive Data Visualisation with R"
            href: "Hands on Exercise/Hands on Exercise_3/Hands-on Exercise_3_1.html"
          - text: "3b. Programming Animated Statistical Graphics with R"
            href: "Hands on Exercise/Hands on Exercise_3/Hands-on Exercise_3_2.html"
          - text: "4a. Visualising Distribution"
            href: "Hands on Exercise/Hands on Exercise_4/Hands-on Exercise_4_1.html"
          - text: "4b. Visual Statistical Analysis"
            href: "Hands on Exercise/Hands on Exercise_4/Hands-on Exercise_4_2.html"
          - text: "4c. Visualising Uncertainty"
            href: "Hands on Exercise/Hands on Exercise_4/Hands-on Exercise_4_3.html"
          - text: "4d. Funnel Plots for Fair Comparisons"
            href: "Hands on Exercise/Hands on Exercise_4/Hands-on Exercise_4_4.html"
          - text: "5a. Creating Ternary Plot with R"
            href: "Hands on Exercise/Hands on Exercise_5/Hands-on Exercise_5_1.html"
          - text: "5b. Visual Correlation Analysis"
            href: "Hands on Exercise/Hands on Exercise_5/Hands-on Exercise_5_2.html"
          - text: "5c. Visual Multivariate Analysis with Heatmap"
            href: "Hands on Exercise/Hands on Exercise_5/Hands-on Exercise_5_3.html"
          - text: "5d. Visual Multivariate Analysis with Parallel Coordinates Plot"
            href: "Hands on Exercise/Hands on Exercise_5/Hands-on Exercise_5_4.html"
          - text: "5e. Treemap Visualisation with R"
            href: "Hands on Exercise/Hands on Exercise_5/Hands-on Exercise_5_5.html"
          - text: "Hands-on Exercise 6"
            href: "Hands on Exercise/Hands on Exercise_6/Hands-on Exercise_6.html"
          - text: "Hands-on Exercise 7"
            href: "Hands on Exercise/Hands on Exercise_7/Hands-on Exercise_7.html"
          - text: "Hands-on Exercise 8"
            href: "Hands on Exercise/Hands on Exercise_8/Hands-on Exercise_8.html"
          - text: "Hands-on Exercise 9"
            href: "Hands on Exercise/Hands on Exercise_9/Hands-on Exercise_9.html"
          - text: "Hands-on Exercise 10"
            href: "Hands on Exercise/Hands on Exercise_10/Hands-on-Exercise_10.html"
      - text: "<img src='/image/timeturner.png' style='height:30px; vertical-align:middle; margin-right:8px;'> Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: "Take-home Exercise/Take-home_Ex_1/Take-home_Ex_1.html"
          - text: "Take-home Exercise 2"
            href: "Take-home Exercise/Take-home_Ex_2/Take-home_Ex_2.html"
          - text: "Take-home Exercise 3"
            href: "Take-home Exercise/Take-home_Ex_3/Take-home_Ex_3.html"
    right:
      - icon: house-fill
        text: " "
        href: index.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
editor: visual